"""initial_schema

Revision ID: 1f7e1cc31ac5
Revises: 
Create Date: 2026-03-21 15:19:11.140373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7e1cc31ac5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotspot_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('geohash', sa.String(length=12), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('last_incident', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotspot_data_geohash', 'hotspot_data', ['geohash'], unique=False)
    op.create_index('ix_hotspot_data_incident_count', 'hotspot_data', ['incident_count'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('person', 'shield', name='userrole'), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=False),
    sa.Column('trigger_lat', sa.Float(), nullable=False),
    sa.Column('trigger_lng', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'resolved', 'escalated', name='incidentstatus'), nullable=False),
    sa.Column('convergence_lat', sa.Float(), nullable=True),
    sa.Column('convergence_lng', sa.Float(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_triggered_at', 'incidents', ['triggered_at'], unique=False)
    op.create_index('ix_incidents_triggered_by', 'incidents', ['triggered_by'], unique=False)
    op.create_table('shields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='shieldstatus'), nullable=False),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.Column('commitment_signed', sa.Boolean(), nullable=False),
    sa.Column('active_hours_start', sa.Time(), nullable=True),
    sa.Column('active_hours_end', sa.Time(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_shields_location', 'shields', ['current_lat', 'current_lng'], unique=False)
    op.create_index('ix_shields_status_verified', 'shields', ['status', 'id_verified'], unique=False)
    op.create_table('incident_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('shield_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('notified', 'responding', 'arrived', 'declined', name='responsestatus'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shield_id'], ['shields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'shield_id', name='uq_incident_responses_incident_shield')
    )
    op.create_index('ix_incident_responses_incident_id', 'incident_responses', ['incident_id'], unique=False)
    op.create_index('ix_incident_responses_shield_id', 'incident_responses', ['shield_id'], unique=False)
    op.create_index('ix_incident_responses_status', 'incident_responses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_responses_status', table_name='incident_responses')
    op.drop_index('ix_incident_responses_shield_id', table_name='incident_responses')
    op.drop_index('ix_incident_responses_incident_id', table_name='incident_responses')
    op.drop_table('incident_responses')
    op.drop_index('ix_shields_status_verified', table_name='shields')
    op.drop_index('ix_shields_location', table_name='shields')
    op.drop_table('shields')
    op.drop_index('ix_incidents_triggered_by', table_name='incidents')
    op.drop_index('ix_incidents_triggered_at', table_name='incidents')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_hotspot_data_incident_count', table_name='hotspot_data')
    op.drop_index('ix_hotspot_data_geohash', table_name='hotspot_data')
    op.drop_table('hotspot_data')
    # ### end Alembic commands ###
